# Generated by Django 4.2.1 on 2023-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtime_number', models.PositiveIntegerField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=15)),
                ('errorMessage', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
