# Generated by Django 4.2.1 on 2023-05-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime', '0002_airtimereceive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtimereceive',
            name='id',
        ),
        migrations.AlterField(
            model_name='airtimereceive',
            name='airtime_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
